addons:
    postgresql: 9.6

matrix:
  include:
    - language: ruby
      cache: bundler
      rvm:
        - 2.6.3
      script:
        - gem install bundler -v 2.1.4
        - cd ruby/
        - bundle install
        - bundle exec rspec
        - cd ../server/
        - bundle install
        - bundle exec rails db:create RAILS_ENV=test
        - bundle exec rails db:migrate RAILS_ENV=test
        - bundle exec rspec

notifications:
  email:
    on_success: never
    on_failure: always
