# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: utf8
  reconnect: false
  pool: 5


development:
  <<: *default
  database: optimal_ci_dev

test:
  <<: *default
  database: optimal_ci_test

production:
  <<: *default
  database: optimal_ci_prod
