default: &default
  adapter: postgresql
  timeout: 5000
  encoding: utf8
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  port: <%= ENV['POSTGRES_PORT'] || '5432' %>
  host: <%= ENV['POSTGRES_HOST'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: optimal_ci_dev

test:
  <<: *default
  database: optimal_ci_test

production:
  <<: *default
  database: optimal_ci
